### ISSUE TITLE
RegexCommandHandler does not handle multiline messages

### ISSUE THREAD

**Issue by asm0dey** [vendelieu/telegram-bot#129]
**Describe the bug**
RegexCommandHandler does not handle multiline messages

**To Reproduce**
1. Create a simple handler like this:
```kotlin
@RegexCommandHandler("/test ?.*")
suspend fun addtopic(user: User, bot: TelegramBot, update: MessageUpdate) {
  println("test successful")
}
```
2. Send message 
```
/test a

b
c
```

Observe that the message is not processed and there is no "test successful" in the log.

**Expected behavior**
The message is processed in this handler, and we can observe the message "test successful" in the log

**Comment by vendelieu** [comment]
Added options parameter for @RegexCommandHandler that helps to pass regex parameters to solve  similar cases
