### ISSUE TITLE
How to send some dynamic data to callback from ininlineKeyboardMarkup ?

### ISSUE THREAD

**Issue by DmitryWake** [vendelieu/telegram-bot#261]
I have case, when I build ininlineKeyboardMarkup with several buttons following way:

```
fun InlineKeyboardMarkupBuilder.gameMarkup(games: List<String>) {
    games.forEach {
        it callback DELETE_GAME
    }
}
```

And I have handler function:

```
@CommandHandler.CallbackQuery([DELETE_GAME])
    suspend fun handleDeleteGame(user: User, bot: TelegramBot, update: CallbackQueryUpdate) {
        // LOGIC
    }
```

I want to send name of the game (String) to handler fun. How can I do that?

I've read wiki and haven't found the answer :(

**Comment by vendelieu** [comment]
if I understand correctly you want to get a parameter from the callback to the handler function, right?

In this case you just need to add this parameter to the callback itself and declare the corresponding parameter in the target function :)

```
fun InlineKeyboardMarkupBuilder.gameMarkup(games: List<String>) {
    games.forEach {
        it callback "deleteGame?name=${it.name}"
    }
}
```

and in target function you just declare:
```
@CommandHandler.CallbackQuery([DELETE_GAME])
    suspend fun handleDeleteGame(name: String, user: User, bot: TelegramBot, update: CallbackQueryUpdate) {
        println(name)
    }
```

**Comment by vendelieu** [comment]
you can read more about there:

https://github.com/vendelieu/telegram-bot/wiki/Update-parsing

https://github.com/vendelieu/telegram-bot/wiki/Activity-invocation

**Comment by DmitryWake** [comment]
It is definetly what I need! Thank you!
