### ISSUE TITLE
How to auto-generate entities for markdown string?

### ISSUE THREAD

**Issue by DmitryWake** [vendelieu/telegram-bot#312]
Hi!

Question is: I have a string like` "**bold** some text [url_name](url)"`. Is there a way to auto-generating entities for this string and send message with this entities to user? Basic `sendMessage { text }.send(user, bot)` sending this like a simple text

Thank you!

**Comment by vendelieu** [comment]
Hey there!
Yes, you can just pass parseMode in options block and everything will work like a charm :)

In general it is the overall approach of the library that optional parameters in a separate block.

See [there].(https://github.com/vendelieu/telegram-bot/wiki/Actions#options)

**Comment by DmitryWake** [comment]
Thank you!
