### ISSUE TITLE
`ClassManagerImpl` class could be open

### ISSUE THREAD

**Issue by d-w-x** [vendelieu/telegram-bot#35]
When I want use library in SpringBoot, to make library's DI works with SpringBoot‘s DI, I have to write:

```kotlin
@Configuration
class BeanCreator(
    @Value("\${telegram.bot.token:}")
    private val botToken: String,
    private val context: ConfigurableApplicationContext
) {
    @Bean
    fun getBot(): TelegramBot {
        val bot = TelegramBot(botToken, "xxx.botController") {
            classManager = object : ClassManager {
                private val instances by lazy { mutableMapOf<String, Any>() }
                override fun getInstance(clazz: Class<*>, vararg initParams: Any?): Any =
                    context.getBean(clazz)?: instances.getOrElse(clazz.name) {
                        if (initParams.isEmpty()) clazz.declaredConstructors.first().newInstance()
                        else {
                            clazz.declaredConstructors.first().newInstance(initParams)
                        }.also { instances[clazz.name] = it }
                    }
            }
        }
        bot.update.setBehaviour {
            handle(it)
        }
        return bot
    }
}
```

In this case, I want to provide a ClassManager but don't acturally want to implement the ClassManager.
Maybe we should make `ClassManagerImpl` open so that users can inherit the class to make small modification. In this case, the code could be write as following:

```kotlin
@Configuration
class BeanCreator(
    @Value("\${telegram.bot.token:}")
    private val botToken: String,
    private val context: ConfigurableApplicationContext
) {
    @Bean
    fun getBot(): TelegramBot {
        val bot = TelegramBot(botToken, "xxx.botController") {
            classManager = object : ClassManagerImpl {
                override fun getInstance(clazz: Class<*>, vararg initParams: Any?): Any =
                    context.getBean(clazz)?: super.getInstance(clazz,initParams)
            }
        }
        bot.update.setBehaviour {
            handle(it)
        }
        return bot
    }
}
// I'm not quite familiar with kotlin, so I'm not sure this code could work.
```

Anyway, maybe this code can add into the [SpringBoot demo](https://github.com/vendelieu/telegram-bot_template/tree/spring-bot) to show how to work with SpringBoot?

**Comment by vendelieu** [comment]
Actually if you want to use spring boot di it will be an extra to use such implementation.
Since spring will take care of handling classes lifecycle and you don't need to make wrapper over it.

There's example of spring di usage: [#1](https://github.com/vendelieu/telegram-bot_template/blob/spring-bot/src/main/kotlin/com/example/springbot/implementation/SpringClassManager.kt) [#2](https://github.com/vendelieu/telegram-bot_template/blob/spring-bot/src/main/kotlin/com/example/springbot/configuration/SpringTelegramBot.kt).

Also from v3 you can keep just top level functions (without class) if you don't need state inside your functions or kotlin objects.

**Comment by d-w-x** [comment]
I wasn't sure before that Springboot could take over ClassManager completely.

It couldn't be better now.

**Comment by d-w-x** [comment]
> Also from v3 you can keep just top level functions (without class) if you don't need state inside your functions or kotlin objects.

Referring the [doc](https://kotlinlang.org/docs/fun-interfaces.html#functional-interfaces-vs-type-aliases), we lost the `fun` before the `interface` ?

```kotlin
package eu.vendeli.tgbot.interfaces

/**
 * Interface which is used to process classes, can be inherited to work with DI libraries.
 *
 * @constructor Create empty I class manager
 */
fun interface ClassManager {
    /**
     * Get instance of Class where Command/Input holds.
     *
     * @param clazz
     * @param initParams
     */
    fun getInstance(clazz: Class<*>, vararg initParams: Any?): Any
}
```

**Comment by vendelieu** [comment]
> I wasn't sure before that Springboot could take over ClassManager completely.
> 
> It couldn't be better now.

If you put `@Component` annotation over your actions holding class, spring should controll lifecycle of class and will keep it singleton, if there's no other configuration for it.
As far as I know :\

In your implementations it will seek for class in spring ecosystem (bean, component etc.) and if it's not found it will use default class manager, so as I said it's like using 2 class managers at same time.

**Comment by vendelieu** [comment]
> > Also from v3 you can keep just top level functions (without class) if you don't need state inside your functions or kotlin objects.
> 
> Referring the [doc](https://kotlinlang.org/docs/fun-interfaces.html#functional-interfaces-vs-type-aliases), we lost the `fun` before the `interface` ?
> 
> ```kotlin
> package eu.vendeli.tgbot.interfaces
> 
> /**
>  * Interface which is used to process classes, can be inherited to work with DI libraries.
>  *
>  * @constructor Create empty I class manager
>  */
> fun interface ClassManager {
>     /**
>      * Get instance of Class where Command/Input holds.
>      *
>      * @param clazz
>      * @param initParams
>      */
>     fun getInstance(clazz: Class<*>, vararg initParams: Any?): Any
> }
> ```

Earlier, when the ClassManager was written, the fun interfaces were in the experimental stage, I remember I looked closely, but I don’t remember why I didn’t take note.
We'll have to see if it's suitable for such case!
