### ISSUE TITLE
Library Enhancement

### ISSUE THREAD

**Issue by d-w-x** [vendelieu/telegram-bot#36]
[Affect method] `declineChatJoinRequest` and `approveChatJoinRequest` and ?(Maybei more)

[Suggestion] Parameter for `User` and `Chat` following convention：
- type `String`: username (@ghost);
- type `Long`: user ID / chat ID;
- type `User`/`Chat`: the object.
- We'd better provide 2 method for each API:  [type `String` + type `User`/`Chat`] / [type `Long` + type `User`/`Chat`], with type `User`/`Chat`, we parse necessary parameter in library.

[Step] Maybe we should slow update this:
1. Mark the origin API as `deprecated`, develop new API and suggest them.
2. Maintain all APIs in some versions.
3. Delete the deprecated API and release a big version.

**Comment by vendelieu** [comment]
For those methods I'm not sure is api supports username option since it's described as `Integer`.
If it's fine with usernames there's already [`Identifier`](https://vendelieu.github.io/telegram-bot/-telegram%20-bot/eu.vendeli.tgbot.types.internal/-identifier/index.html) class in library for such cases.

**Comment by d-w-x** [comment]
> We'd better provide 2 method for each API: [type String + type User/Chat] / [type Long + type User/Chat], with type User/Chat, we parse necessary parameter in library.

I means that:
- If the telegram API asked for username, we supply 2 method in our library: [type `String` + type `User`/`Chat`];
- If the telegram API asked for id, we supply 2 method in our library: [type `Long` + type `User`/`Chat`];
- If username and id are both acceptable, we supply 3 method in our library: [type `String` + type `Long` + type `User`/`Chat`];

**Comment by vendelieu** [comment]
To determine chat identifier there is already a generic method for interface `Action` and `MediaAction`.
For all other methods, I added overload methods with the ability to pass `User` (actually, there aren't that many of them).

**Comment by d-w-x** [comment]
Thanks for the following up, I think it's time to mark this question as done!
