### ISSUE TITLE
Actions are not found in controller if it has public unannotated methods

### ISSUE THREAD

**Issue by Sintexer** [vendelieu/telegram-bot#39]
**Describe the bug**
I've added a non-private helper method to a controller. I didn't make it private by mistake, but this occasion made **TelegramActionsCollector** find a total of 2 actions instead of 6 expected. So I commented out this new method and then all actions were found. I didn't find any documentation on that case, so I suppose it isn't intended behavior

**To Reproduce**

1. Create controller with an action. Make sure your action is found during start-up process
2. Add another public method to your controller
3. Not during start-up, your action won't be found

**Expected behavior**
I expect that any amount of public/private methods could be added to controller without interfering with work of telegram bot api library

**Screenshots**

With public helper method, 2 actions in total

![image](https://github.com/vendelieu/telegram-bot/assets/13377115/24a40813-c9eb-485d-9ec0-0157818264dc)

With private helper method, 6 actions in total
![image](https://github.com/vendelieu/telegram-bot/assets/13377115/d216ac85-26c8-429c-adbc-4933c87b289b)

**Additional context**
No stacktrace or error log were produced
P.S. I do enjoy your lib

**Comment by vendelieu** [comment]
Thank you very much for your report!

Yes, the library that is used for reflection sometimes produces such implicit bugs.
I've been waiting for some time for the opportunity to transfer to another library and improve this point.
Otherwise, I will need to separately write a library which is an overhead.

I'm very glad that you liked the library!
I hope it will make your development easier in the future, if there are any suggestions, I’m completely open to them!

**Comment by vendelieu** [comment]
For your case you can store keyboard in val:

```kotlin
private val newConceptEditKeyboard = inlineKeyboardMarkup {
  "lorem" callback "ipsum"
  //...
}
// ... in your handler function:
message { "dolor" }.markup(newConceptEditKeyboard).send(to, via)
```

**Comment by Sintexer** [comment]
You're right. It is also totally fine with private function. Just knew I have to report it.

**Comment by vendelieu** [comment]
Yeah, it's good to mention problem that may exist!
Thank you very much!
